### ISSUE TITLE
instalation error and Please add English 

### ISSUE THREAD

**Issue by ammlr** [a406010503/Miui_Camera#10]
I'm having problems with the installation, when pressing volume (+), installation fails . and please use English for installation, not everyone understand Chinese 

![Screenshot_2022-09-25-10-56-56-881_m dekydtx rrg](https://user-images.githubusercontent.com/30746607/192127695-659f6467-3c50-40a0-b5ab-790ce4b9dc87.jpg)

**Comment by a406010503** [comment]
currently will only support chinese installer
**[Miui_Camera_4.5.000851.0_220924](https://github.com/a406010503/Miui_Camera/releases/tag/Miui_Camera_4.5.000851.0_220924)**
> ### Important warning
> - Since the installation script only supports traditional Chinese, if you cannot understand the question, it is recommended that you take a screenshot and use Google Translate to upload the screenshot to try to answer the question
