### ISSUE TITLE
街拍模式静音

### ISSUE THREAD

**Issue by huziiyu** [a406010503/Miui_Camera#11]
最新的徕卡版本里有街拍模式，但是关闭不了声音，如果可以的话可以加入静音吗

**Comment by a406010503** [comment]
您可以自行替換官方的音檔（原版本為無聲）
`/res/raw/camera_click_cv.ogg`

**Comment by huziiyu** [comment]
感谢您的耐心解答！！但我由于是修补boot刷的面具，没办法解锁system分区修改系统软件，把此音档修改后无法刷入，请问您接下来会有考虑推出带有静音街拍功能的版本吗？如果没有这个计划那我再想办法，总之还是感谢您了！

**Comment by a406010503** [comment]
這裡並不是要您替換系統檔案... 而是修改該 Magisk 模組內的相機 Apk 檔案，將該相機 Apk 的 `/res/raw/camera_click_cv.ogg` 進行替換，您可以使用MT管理器之類的檔案管理器進行此操作。

**Comment by huziiyu** [comment]
收到，感谢您的解答，已经修改成功

**Comment by a406010503** [comment]
最新版本的 Dev 引入了街拍無聲特性，您可以試試看
