### ISSUE TITLE
深夜拍照问题

### ISSUE THREAD

**Issue by jin2005213** [a406010503/Miui_Camera#12]
拍照后打开图片为什么有那么多的小星星，还有自动夜景的问题，机型是k50pro![IMG_20221014_195833.jpg](https://user-images.githubusercontent.com/114378503/195843003-181e9cda-31d1-47ba-884b-5e2b205cdc4e.jpg)![IMG_20221014_194110.jpg](https://user-images.githubusercontent.com/114378503/195843030-41c5cd42-612c-420f-8ee7-2c82cc7cd0f6.jpg)

**Comment by a406010503** [comment]
告知使用的版本，如果是體驗版則不接受反饋。

**Comment by a406010503** [comment]
由於此問題不再活躍，此 issue 將關閉。
如後續有任何需要，您可以重新開啟此 issue 或 open new issue.
