### ISSUE TITLE
4k 60 fps 錄製視頻但不保存任何內容，錄製後沒有文件請修復。

### ISSUE THREAD

**Issue by Parylo-D** [a406010503/Miui_Camera#13]

**Comment by a406010503** [comment]
請告知機型，並且在Releases版上使用它...
若它仍然不起作用就是硬體不支援

**Comment by Parylo-D** [comment]
小米 11 Lite 5G NE。在以前的版本中，一切正常，並且在備用相機上一切正常。

ср, 2 лист. 2022, 19:35 користувач 聖小熊 ***@***.***> пише:

**Comment by a406010503** [comment]
以前的版本是哪個版本呢?

**Comment by Parylo-D** [comment]
我不記得了。我知道在 5 個版本之前的某個地方，一切正常。之後，連續 5 次更新不再起作用。

ср, 2 лист. 2022, 19:45 користувач 聖小熊 ***@***.***> пише:

**Comment by a406010503** [comment]
4870之前的版本嗎? 或許在511版本後因為仍處於A13測試環境，在部分機型上出現一些小問題難免的。
我們檢查了一下，在錄影上除了只有開啟強制全機型60Fps外，並沒有做其他的更動。
如果你真的想使用這個功能，建議回退到它可以使用的版本

**Comment by a406010503** [comment]
由於此問題不再活躍，此 issue 將關閉。
如後續有任何需要，您可以重新開啟此 issue 或 open new issue.
