### ISSUE TITLE
小米12x使用專業模式開raw格式，JPG文件會出現三條暗線

### ISSUE THREAD

**Issue by apchuzh** [a406010503/Miui_Camera#14]
![IMG_20221103_162622_2](https://user-images.githubusercontent.com/117504099/200106265-f5790c1e-a26d-4d32-a228-11a374dea6d1.jpg)

**Comment by apchuzh** [comment]
版本是v4.5.001110.0 (221102-Leica)

**Comment by a406010503** [comment]
之前的版本有沒有這問題呢?

**Comment by a406010503** [comment]
由於此問題不再活躍，此 issue 將關閉。
如後續有任何需要，您可以重新開啟此 issue 或 open new issue.
