### ISSUE TITLE
Dynamic Shots Not Working

### ISSUE THREAD

**Issue by abdoelbanaa** [a406010503/Miui_Camera#16]
Hi brother's the feature Dynamic Shot Note working in some devices please can force showing and working in any device!?

**Comment by abdoelbanaa** [comment]
> Hi brother's the feature Dynamic Shot Note working in some devices please can force showing and working in any device!?

Ad my phine is Redmi Note 10

**Comment by a406010503** [comment]
你是說動態照片嗎?

**Comment by abdoelbanaa** [comment]
> do you mean dynamic photos?

No i mean dynamic shots in photo

**Comment by a406010503** [comment]
Dynamic shots are already mandatory on all devices, don't you?

**Comment by abdoelbanaa** [comment]
> Dynamic shots should be mandatorily enabled on all devices, don't you have this feature?

Yes, I do not have it and it is present in some other phones. Please solve this problem and review the codes

**Comment by a406010503** [comment]
Please check if the latest version has been fixed... [Click](https://github.com/a406010503/Miui_Camera/releases/tag/Miui_Camera_4.5.001180.0_221113)

**Comment by abdoelbanaa** [comment]
> Please check if the latest version has been fixed... [Click](https://github.com/a406010503/Miui_Camera/releases/tag/Miui_Camera_4.5.001180.0_221113)

Yeah bro working and the best version everyway

**Comment by abdoelbanaa** [comment]
Fixed
