### ISSUE TITLE
Camera disappear after last update why?

### ISSUE THREAD

**Issue by Pampurios** [a406010503/Miui_Camera#17]
hi i updated the camera to today's version. after restarting the phone with magisk the camera disappears. i no longer have the icon in the launcher and there is no trace of it. previous version all ok. thank you guys

**Comment by a406010503** [comment]
We will try to fix this issue in the next fix version, until then we recommend to watch the modification instructions and install it with Core Patch.

**Comment by Pampurios** [comment]
Thank you. I will try the fix. Good job 👍

**Comment by a406010503** [comment]
New version 221115 has been released, try to see if it solves.

**Comment by jfcherng** [comment]
After installing today's `Magisk-MIUI_Camera-Leica-v221115-release.zip`, my camera disappers as well. Rollback to `Magisk-MIUI_Camera-Leica-v221113-release.zip` and the camera appears again.

**Comment by rsps1008** [comment]
My 221115 will disappear…, but 221113 is normal on my mi 12 pro in MIUI11 Eu ROM 13.0.41

**Comment by jfcherng** [comment]
Most likely you guys didn't install LSPosed + Core Patch.

**Comment by rsps1008** [comment]
Yes, sure I didn't. To be fair, I don't want to install LSPosed if I don't must to, and I can used the module normally before 221113. I think I should stay at version 221113 if I have to install LSPosed in the future, thank you for your reply.

**Comment by a406010503** [comment]
Check if version 221117 is available.

**Comment by a406010503** [comment]
Since this issue is no longer active, we will close this issue.

The problems mentioned in this issue will continue to be optimized in subsequent versions.
