### ISSUE TITLE
12S Ultra + miui eu v13.0.11.0 更新最新module后徕卡功能失效

### ISSUE THREAD

**Issue by xenoninja** [a406010503/Miui_Camera#18]
更新到最新module v4.5.001180.0 (221113)后，打开相机APP，发现没有徕卡功能，在设置中打开徕卡相机介面并重启APP后，仍然没有徕卡功能

PS: 使用老版本[v4.5.001180.0 (221108-Leica)]，徕卡功能正常

**Comment by xenoninja** [comment]
![Screenshot_2022-11-14-15-38-59-488_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/13446393/201605117-3b80a3e5-55a2-4d70-a3d9-b4369c6f9a8d.jpg)

**Comment by a406010503** [comment]
關閉它重啟相機
再將它再次打開後重啟相機
若無效建議清除相機所有數據後再嘗試一次

**Comment by xenoninja** [comment]
将功能关闭再打开后可以了，thx
