### ISSUE TITLE
Port request for K20 Pro(Raphael/ Mi 9T pro)

### ISSUE THREAD

**Issue by singhh9596** [a406010503/Miui_Camera#20]
Can you please port miui_camera for k20 Pro (mi 9T pro) as well? Using ANX Camera and it has broken 48mp and potrait mode.

**Comment by a406010503** [comment]
Unfortunately, we can't add profiles for each model, Xiaomi adds a lot of obfuscated code which makes it hard to find... We recommend using Telegram's [@sipollo](https://t.me/sipolloMOD) Camera MOD, which has a Xiaomi Leica camera for the K20 Pro based on the 4870 version...

**Comment by singhh9596** [comment]
That's unfortunate. And about the module you suggested, I've already tested it and it didn't flashed in Raphael. Thanks by the way

**Comment by a406010503** [comment]
You can find it here... [Link](https://t.me/sipolloMOD/308)
As this is out of my scope, I will close this question, if you have any questions you can reopen this
