### ISSUE TITLE
Track move objects Bug

### ISSUE THREAD

**Issue by abdoelbanaa** [a406010503/Miui_Camera#21]
Hi , The feature Moving Track not working why and after open video mode and tap to Track Move Object And touch screen The Camera Force Close Please Can fix it 

@a406010503 
![Screenshot_2022-11-19-19-33-43-011_com android camera](https://user-images.githubusercontent.com/107816648/202888299-cb4cf42d-1e23-405e-b03a-99ff34a8c4ee.jpg)

**Comment by a406010503** [comment]
This feature may not be supported on all devices, which is a problem we tend to encounter with camera patching, which usually happens on phones that have been launched for a long time...

**Comment by a406010503** [comment]
This issue will be closed as this issue is no longer active.
If you need anything later, you can reopen this issue or open a new issue.
