### ISSUE TITLE
Disable Parallel Processing for Portrait mode?

### ISSUE THREAD

**Issue by ItzDFPlayer** [a406010503/Miui_Camera#22]
Is there's any way to disable Parallel Processing only for Portrait mode, I'm making Mi 9T/Pro (davinci/raphael) port, the only thing is broken right now is back Portrait while it's enabled, I'm checking code right now, but maybe you know more

**Comment by a406010503** [comment]
Maybe you can turn it off in lab mode...

**Comment by ItzDFPlayer** [comment]
I know, it works like that, just curious if there's some check for paralleprocess in portrait to break in my port

**Comment by a406010503** [comment]
We don't know how it works for the time being. For K20 Pro, other authors made it, you can refer to the following telegram link: [Click me](https://t.me/sipolloMODgroup/61618)

**Comment by a406010503** [comment]
This issue will be closed as this issue is no longer active.
If you need anything later, you can reopen this issue or open a new issue.
