### ISSUE TITLE
Document Mode Not Working 

### ISSUE THREAD

**Issue by abdoelbanaa** [a406010503/Miui_Camera#23]
Hi Bro The Document Mode Mode not working after shatter the photo not showing in selector for editing and save this photo please Solve the Problem

**Comment by a406010503** [comment]
In some models may appear in the error, guess for the Xiaomi problem, please wait for the next version whether to fix.

**Comment by ItzDFPlayer** [comment]
That happens when app Bokeh (MiuiExtraPhoto) isn't installed or really old version

**Comment by a406010503** [comment]
Since this issue is no longer active, we will close this issue.

The problems mentioned in this issue will continue to be optimized in subsequent versions.
