### ISSUE TITLE
红米NOTE9PRO能优化下HDR吗？

### ISSUE THREAD

**Issue by qiang312040113** [a406010503/Miui_Camera#24]
红米NOTE9PRO开启HDR后对焦亮度区域就过曝，对焦暗部区域就整体过暗。希望能优化一下。

**Comment by a406010503** [comment]
有樣張嗎，確認的話會在下個版本嘗試修復

**Comment by qiang312040113** [comment]
![谷歌亮处对焦IMG4 Dec 23_12 Rudra LMC 8 4 r14 v1 (1)](https://user-images.githubusercontent.com/54388139/205641029-aa3eab7a-c5f2-4e70-988f-c8353a46f446.jpg)
开启关闭HDR的都有，还有自动对焦的，一张谷歌相机的。

**Comment by a406010503** [comment]
針對您的機型出現過曝問題，問題將會在下一次更新時修復
