### ISSUE TITLE
街拍模式 不能錄影 （MI11 Lite 5G）

### ISSUE THREAD

**Issue by tkrave** [a406010503/Miui_Camera#25]
EU修改版ROM的街拍模式可以選擇街拍模式A（連拍）或B （錄影 ）。
安裝了徠卡相機MOD之後街拍模式沒有了選項，只能ON/OFF啓動連拍功能。
請問能不能回復街拍模式A/B選項還原錄影功能？

**Comment by a406010503** [comment]
那是EU的功能，只能等待EU更新最新版本的相機我們才有可能跟進...

**Comment by a406010503** [comment]
不...這個功能是EU自己加的，就算不是徠卡也是沒有街拍錄影功能的，而且這個要做因為相當複雜，因此我們更傾向於EU修改後我們進行合併。

**Comment by JerryShih** [comment]
@a406010503
請問readme裡寫的
```
街拍錄影模式僅限EU修改版可以使用
```
`EU修改版` 就是指 `xiaomi.eu` rom 嗎？ 還是那一個版本？ 我用 eu rom weekly 開發版也只能拍照不能錄影

**Comment by JerryShih** [comment]
Oh.. I got the answer from eu forum.

**Comment by a406010503** [comment]
@JerryShih 
意思是從 EU 系統裡提取的修改版相機。
我們嘗試在最新 1620 版本加入街拍錄影
但是此功能目前來看不起作用，而 EU 團隊也沒有修的打算
可能是時候和他說再見了
