### ISSUE TITLE
Parallel processing 

### ISSUE THREAD

**Issue by Samatulli** [a406010503/Miui_Camera#26]
When I turn on parallel processing, the camera closes with an error. If you turn it off, then the quality in the photos deteriorates very much. can this be fixed somehow? Xiaomi 12T, Dimensity 8100

**Comment by Samatulli** [comment]
Please help

**Comment by a406010503** [comment]
Since this issue is no longer active, we will close this issue.

The problems mentioned in this issue will continue to be optimized in subsequent versions.
