### ISSUE TITLE
Mi11 Ultra變焦倍率按鈕元素重疊

### ISSUE THREAD

**Issue by HLEndman** [a406010503/Miui_Camera#29]
![Screenshot_2022-12-13-01-54-27-593_com android camera](https://user-images.githubusercontent.com/36873959/207118701-7126ced4-9960-4082-a344-364ab0960f03.jpg)
相機版本號v4.5.001180.0 (221208) 
release與dev均有此現象
手機版本
22.10.26 MIUI13 Android12
14.0.22.12.5.DEV Android13
均有此現象

**Comment by HLEndman** [comment]
![Screenshot_2022-12-13-10-37-44-962_com android camera](https://user-images.githubusercontent.com/36873959/207212617-dc961511-5206-49ea-91b2-f43222c4d4ba.jpg)

**Comment by a406010503** [comment]
The latest version has been released to fix this issue, so we will close this issue, if you have other issues you can reopen it or create a new one.
