### ISSUE TITLE
8k only 24 fps

### ISSUE THREAD

**Issue by 00raq00** [a406010503/Miui_Camera#3]
In prerelease [v4.3.004750.0 (220709)] on my Apollo pro (mi 10t pro) i can see that 8k video is supported only with 24 fps. Stable and stock camera support 8k 30 fps 😉

**Comment by a406010503** [comment]
The pre-release version may encounter various issues, in which case I will ask the original author who made this camera version to see if there is a solution.

**Comment by 00raq00** [comment]
Cool thx

**Comment by a406010503** [comment]
Try to update the version of 220710~220711

**Comment by 00raq00** [comment]
Yeap it works
