### ISSUE TITLE
相机一直出现闪退

### ISSUE THREAD

**Issue by WhoIAmilet** [a406010503/Miui_Camera#32]
[已经删除了对应的Miui_Camera再次重新刷入模块,但相机一直无法打开，一直闪退，已经更新到221213版本，]
![07cbb3c64df64989f652375f5c8d199](https://user-images.githubusercontent.com/120651185/207920252-cb71ae05-4a3b-43ec-941e-58c65d6b6d9a.jpg)
![d1ae69f93dacaf54a03ac24658146dc](https://user-images.githubusercontent.com/120651185/207920266-ae01b383-5bca-4ddd-b5b3-114858b99fa2.jpg)
![8989d5cf88b7321adcdadcc36849893](https://user-images.githubusercontent.com/120651185/207920297-8571faa2-2353-42ce-80af-5ca1ab65bdff.jpg)

**Comment by a406010503** [comment]
先確認是否其他模塊造成... 既然已經刪除模塊應該就不是我的問題
另外，請嘗試清除 /data/system/package-cache/ 底下的文件，並重啟您的手機

**Comment by a406010503** [comment]
順便問一句，你是否更新到 MIUI 14 了?  目前模塊尚未適配 MIUI 14，請使用核心破解方式安裝相機。

**Comment by WhoIAmilet** [comment]
并未更新到miui14，目前版本为miui13.0.24，已经试着清除cache，并未奏效，在酷安平台也看到相机闪退的反馈。最后我选择了清除所有手机数据重新安装，现在已经可以正常使用。
我猜测可能是安装相机补全模块后，在恢复手机备份时安装了系统的相机文件导致。

发件人: 聖小熊 ***@***.***>
发送时间: 2022年12月16日 0:59
收件人: a406010503/Miui_Camera ***@***.***>
抄送: WhoIAmilet ***@***.***>; Author ***@***.***>
主题: Re: [a406010503/Miui_Camera] 相机一直出现闪退 (Issue #32)


順便問一句，你是否更新到 MIUI 14 了? 目前模塊尚未適配 MIUI 14，請使用核心破解方式安裝相機。
