### ISSUE TITLE
慢动作超慢速调节失效

### ISSUE THREAD

**Issue by Chen017** [a406010503/Miui_Camera#33]
小米11Pro miui13 10.26 Android 12 近期最新版本 拍摄1080p 1920 fps慢动作后 进入相册 无法进行超慢速调节 卸载更新后使用原版的则正常
![Screenshot_2022-12-17-19-26-13-636_com miui gallery](https://user-images.githubusercontent.com/120784851/208240351-33046930-fd28-4078-a83f-ec7bf0b2b21f.jpg)
![IMG_20221217_192644](https://user-images.githubusercontent.com/120784851/208240356-907933c3-67d8-4750-984c-ed44ad56bc90.jpg)

**Comment by a406010503** [comment]
該版本未修改相機也是這樣的，估計是小米的問題，但是經過測試在選擇 120FPS 時是可以做慢速調節的，您可以嘗試看看。
由於無法修復該問題我將關閉此 issues，如果您有其他問題，可以重新打開此 issues 或另建一個新 issues。
