### ISSUE TITLE
Not working on miui 14

### ISSUE THREAD

**Issue by DarkHacker2k223** [a406010503/Miui_Camera#34]
When can this module support MIUI14? Now do you plan to port it on MIUI14?

**Comment by a406010503** [comment]
We currently have no plans to support the Magisk module for MIUI 14 as it may have serious issues on some models. It is recommended that you unzip the camera in the installation package and install it directly with Core Patch

**Comment by DarkHacker2k223** [comment]
It now works on MIUI 14
![Screenshot_2022-12-21-06-04-41-530_com android settings](https://user-images.githubusercontent.com/71393195/208783341-869ada87-4952-4a94-aa6a-0367d2466eab.jpg)
![Screenshot_2022-12-21-06-04-51-660_com android camera](https://user-images.githubusercontent.com/71393195/208783361-073abb35-f192-4df9-8ca9-1d8b6b8ff334.jpg)
. but have to bring the first version to flash
