### ISSUE TITLE
3.7x zoom button in Mi Note 10/CC9 Pro

### ISSUE THREAD

**Issue by rzt12** [a406010503/Miui_Camera#35]
when the 3.7x zoom button is pressed, the lens used is 2x optical, instead of the 3.7x optical in the Mi Note 10/CC9 Pro

**Comment by a406010503** [comment]
Since Xiaomi CC9 Pro / Xiaomi Note 10 is about to be unsupported, this issue may not be fixed, and we don't know how to fix this issue, because it works fine on my Xiaomi 10 Pro...

**Comment by rzt12** [comment]
well, now I understand what the problem is. thanks for the elaboration of the problem.

**Comment by rzt12** [comment]
sorry in advance, I found 1 Problem again, for the device name on the leica watermark it says redmi note 10, not mi note 10, can it be fixed?

**Comment by a406010503** [comment]
@rzt12 This issue will be checked and please verify this issue in the next release

**Comment by rzt12** [comment]
![IMG_20221218_215913_578](https://user-images.githubusercontent.com/120946294/208305457-d6c8f2bb-406a-440d-84a0-8857315a9e0b.jpg)

**Comment by rzt12** [comment]
well, thank you very much for the response and thank you very much for creating and developing this cool and great mod camera app. I really like and comfortable using it. Hopefully, this project will continue and grow. We will always wait for its development and will also continue to support you and your team 😊
