### ISSUE TITLE
k20pro miui13 

### ISSUE THREAD

**Issue by conancheng** [a406010503/Miui_Camera#37]
上个版本还可以打的开，最新版本就直接打不开相机了![Screenshot_2022-12-14-08-14-55-663_com.android.settings.jpg](https://user-images.githubusercontent.com/24214834/208455763-28924a17-62ef-4f10-86d2-3172ec012111.jpg)

**Comment by a406010503** [comment]
K20 series is no longer supported since a long time ago, please use the earlier version or use other people's modified MOD...
