### ISSUE TITLE
Xiaomi 11i

### ISSUE THREAD

**Issue by xShihaBx** [a406010503/Miui_Camera#39]
Camera app uninstalled after flashing

**Comment by a406010503** [comment]
What version do you have installed? What is the system?

**Comment by xShihaBx** [comment]
The latest version
Miui 13

**Comment by xShihaBx** [comment]
Previous versions were working properly

**Comment by a406010503** [comment]
Please check if you have installed MIUI13 version, the version with MIUI14 is not available.
If it still does not work, we recommend using Core Patch to install the camera.

**Comment by a406010503** [comment]
Check that the latest versions of 221222 and 221222T are working.

**Comment by a406010503** [comment]
由於此問題不再活躍，我們將關閉此問題。

本次提到的問題會在後續版本中持續優化。
