### ISSUE TITLE
480 fps missing on mi 10t pro

### ISSUE THREAD

**Issue by 00raq00** [a406010503/Miui_Camera#4]
Using prerelease v4.3.004700.1 on my mi10t pro i cannot use 480 fps slow motion. This feature is working on latest stable.

Maybe it is possible to enable it on "leica" version 😉

**Comment by a406010503** [comment]
Yes, the MI10T series is not compatible with 480Fps slow motion on this version
Since we have decided not to maintain the Leica version of the camera (too many bugs to deal with)
We recommend that you use the official version 4.3.003591.0 (220501) of this project for a better experience.

**Comment by 00raq00** [comment]
> 

Your link directs to v4.3.004700.1 😉 that i have installed

**Comment by 00raq00** [comment]
If you will have any experimental version (non public prerelease) i can install and test 😉

**Comment by a406010503** [comment]
This version has just tried to modify 480Fps, please confirm whether it can be used normally.

**Comment by 00raq00** [comment]
![Screenshot_2022-07-14-16-39-56-543_com android camera](https://user-images.githubusercontent.com/135963/179009087-38ef1488-bd97-4b08-b607-dc8d6d3297c0.jpg)
There is missing slow motion 🙄

**Comment by a406010503** [comment]
Is this switch normal in the last version?

**Comment by 00raq00** [comment]
Yeap it is available:

Camera settings -> customise -> feature layout

**Comment by 00raq00** [comment]
Hmm let me summarize...

Slow motion is missing on 
[v4.3.004700.1 (220711-Preview)](https://github.com/a406010503/Miui_Camera/releases/tag/Miui_Camera_4.3.004700.1_220711)
Pre-release

Slow motion is available but only 120 fps on 
v4.3.004870.0 (220711-Preview)
Pre-release

**Comment by a406010503** [comment]
Still no 480Fps? If it still doesn't, then I may need some time to test the problem so as not to inconvenience you.

**Comment by a406010503** [comment]
This is the last modification, if it is still not available or there is no slow-motion 480Fps option, it may be that the Leica camera cannot be adapted, or Xiaomi has forced this option to be limited.
The download link is the same, please download and flash again.

**Comment by a406010503** [comment]
We took another look at the problem today for the Mi 10T Pro
You should be able to get fixes in this version, so please let me know if it's still buggy.
[Apk-MIUI_Camera-Leica-v220804-release.apk](https://github.com/a406010503/Miui_Camera/releases/download/Miui_Camera_Leica_4.3.004870.0_220801/Apk-MIUI_Camera-Leica-v220804-release.apk)

**Comment by 00raq00** [comment]
> We took another look at the problem today for the Mi 10T Pro You should be able to get fixes in this version, so please let me know if it's still buggy. [Apk-MIUI_Camera-Leica-v220804-release.apk](https://github.com/a406010503/Miui_Camera/releases/download/Miui_Camera_Leica_4.3.004870.0_220801/Apk-MIUI_Camera-Leica-v220804-release.apk)

Still doesn't work 🙄

![Screenshot_2022-08-03-19-06-05-924_com miui bugreport](https://user-images.githubusercontent.com/135963/182667741-a6645049-253c-40dc-ad90-da3632a87fc3.jpg)

**Comment by a406010503** [comment]
Your question should be the same as reflected in #5
If you already have 480Fps and it's still not available, the Leica may not be able to adapt
I'm sorry about that!
In this release we also fixed the bug that the 10T Pro could not use the magic clone and watermark error
Hope you enjoy this project to the fullest!

**Comment by a406010503** [comment]
If there are no other problems, I will close this issue first, and if there are other problems, you can submit feedback again!

**Comment by a406010503** [comment]
We've released a version that fixes a number of issues, and you should be able to get those fixes in this release.
I'll merge into the release channel once it's stable.
[v4.3.004870.0 (220806-Leica-Preview)](https://github.com/a406010503/Miui_Camera/releases/tag/Miui_Camera_4.3.004870.0_Pre_220806)

**Comment by 00raq00** [comment]
Works fine thx
