### ISSUE TITLE
Redmi k20 pro issue 

### ISSUE THREAD

**Issue by hardikdesai97** [a406010503/Miui_Camera#41]
![Screenshot_2022-12-22-10-30-54-795_com android camera](https://user-images.githubusercontent.com/53992875/209061025-37f53bb7-3bd8-4be7-b3a1-efcea47eb330.jpg)

Miui Leica camera work in redmi k20 pro but need to disable dual SAT and parallel processing
I hope dev can fix this in next update

**Comment by a406010503** [comment]
Since my support for the K20 series is an experiment, we can't guarantee that it will work reliably and I will look into this area.

**Comment by hardikdesai97** [comment]
thanks for good response

**Comment by a406010503** [comment]
Check that the latest versions of 221222 are working.

**Comment by a406010503** [comment]
The problem is that the feedback we receive is that in most cases you have to turn it off to get it to work, and the K20 Pro has been off the list of supported models for a long time, so we can't fix this problem...
