### ISSUE TITLE
刷了v4.5.001620.2（221220）版后相机的app就消失不见了，无法使用相机

### ISSUE THREAD

**Issue by yuejunwudi** [a406010503/Miui_Camera#42]
我是小米11青春版，刷了v4.5.001620.2（221220）版后相机的app就消失不见了，无法使用相机。
从magisk移除模块后相机app就回来了。magisk版本ed37ddd5-alpha（25205），手机是安卓13，miui14开发版。
![Screenshot_2022-12-22-13-45-01-865_io github vvb2060 magisk](https://user-images.githubusercontent.com/95584196/209065646-6c3c6dad-6673-45ab-a02c-7bd1cd182d79.jpg)
![Screenshot_2022-12-22-13-45-08-549_io github vvb2060 magisk](https://user-images.githubusercontent.com/95584196/209065659-a6d8d111-5ac7-4e35-b837-802ae5397dfa.jpg)
![Screenshot_2022-12-22-13-45-26-919_com android settings](https://user-images.githubusercontent.com/95584196/209065688-e32e3272-6f33-4f0b-afdc-33b2ee679f98.jpg)

**Comment by a406010503** [comment]
模塊導致相機丟失問題猜測為更改版本號所致，因為之前也有因為更改版本號導致類似的情形，這是小米所做的嚴格的簽名校驗導致的，我們會在下個版本回復他的版本號，並將修改後的版本號另做一個 APK 上傳他。

**Comment by a406010503** [comment]
檢查最新版本 221222 與 221222T 是否正常。

**Comment by yuejunwudi** [comment]
感谢大佬更新，麻烦大佬了。
我刷入了这两个版本Magisk-MIUI_Camera-v221222-Pre-dev-MIUI14.zip和Magisk-MIUI_Camera-Leica-v221222-release-MIUI14.zip还是有问题，刷完以后相机app消失不见了。 另外安装Apk-MIUI_Camera-v221222.apk安装不成功 提示“安装包解析出错”。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月22日(周四) 晚上6:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [a406010503/Miui_Camera] 刷了v4.5.001620.2（221220）版后相机的app就消失不见了，无法使用相机 (Issue #42)




 
檢查最新版本 221222 與 221222T 是否正常。
