### ISSUE TITLE
v221222版本刷入后相机app还是存在消失不见的问题

### ISSUE THREAD

**Issue by yuejunwudi** [a406010503/Miui_Camera#43]
感谢大佬更新，麻烦大佬了。
我刷入了这两个版本Magisk-MIUI_Camera-v221222-Pre-dev-MIUI14.zip和Magisk-MIUI_Camera-Leica-v221222-release-MIUI14.zip还是有问题，刷完以后相机app消失不见了。 另外安装Apk-MIUI_Camera-v221222.apk安装不成功 提示“安装包解析出错”。
magisk版本ed37ddd5-alpha（25205），手机是安卓13，miui14开发版。
![Screenshot_2022-12-22-13-45-26-919_com android settings](https://user-images.githubusercontent.com/95584196/209122519-2d609d15-7f36-44e7-90f1-7bd43ca5b512.jpg)
![Screenshot_2022-12-22-13-45-01-865_io github vvb2060 magisk](https://user-images.githubusercontent.com/95584196/209122587-f0314cfc-c576-4d7c-90cd-2f2124950ad4.jpg)
![Screenshot_2022-12-22-18-50-56-119_com miui packageinstaller](https://user-images.githubusercontent.com/95584196/209122684-39805a41-49f6-496b-a083-3f38084be459.jpg)

**Comment by a406010503** [comment]
不是很清楚為什麼會這樣，建議如果行不通只能用核心破解方式安裝他。
修改說明裡面我們有提供相關步驟，請仔細閱讀它。

**Comment by yuejunwudi** [comment]
感谢大佬了。
安装Apk-MIUI_Camera-v221222.apk时提示“安装包解析错误”，不是说不能降级或者签名不正确，“核心破解”用不上呃。


我的手机刷以前的版本“Magisk-MIUI_Camera-v221203-Pre-dev.zip”是正常的，我现在刷回旧版本了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月22日(周四) 晚上7:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [a406010503/Miui_Camera] v221222版本刷入后相机app还是存在消失不见的问题 (Issue #43)




 
不是很清楚為什麼會這樣，建議如果行不通只能用核心破解方式安裝他。
 修改說明裡面我們有提供相關步驟，請仔細閱讀它。

**Comment by yuejunwudi** [comment]
报告大佬，刷Magisk-MIUI_Camera-v221222T-Pre-dev-MIUI14.zip，带T的已经可以完全正常使用了，感谢大佬。
