### ISSUE TITLE
Dynamic Shot not working

### ISSUE THREAD

**Issue by abdoelbanaa** [a406010503/Miui_Camera#44]
After update for a latest version dynamic Shot disappeared 
![Screenshot_2022-12-22-15-57-48-176_com android camera](https://user-images.githubusercontent.com/107816648/209150321-b05f97fe-b138-4ffa-b992-05bf81005894.jpg)

**Comment by abdoelbanaa** [comment]
Model : redmi note 10 
Android 12

**Comment by a406010503** [comment]
Thanks for the report, it will be fixed in the next version.

**Comment by abdoelbanaa** [comment]
> Thanks for the report, it will be fixed in the next version.

Ok will wait it ..
