### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by Chen017** [a406010503/Miui_Camera#45]
![Screenshot_2022-12-23-08-21-44-931_com android camera](https://user-images.githubusercontent.com/120784851/209247340-6d82a379-6f72-4b69-be92-fac33c22199e.jpg)
![Screenshot_2022-12-23-08-22-06-801_com android camera](https://user-images.githubusercontent.com/120784851/209247344-948fb102-fa83-4f18-837d-f06a0e0941db.jpg)
第一个延时摄影中 相机设置里的延时摄影与延时摄影模式功能重复 可以删掉相机设置里的延时摄影速度
![Screenshot_2022-12-23-08-26-30-449_com android camera](https://user-images.githubusercontent.com/120784851/209247451-28801230-c0c1-47b5-a6f9-4f20eb6e539e.jpg)
![Screenshot_2022-12-23-08-26-27-582_com android camera](https://user-images.githubusercontent.com/120784851/209247690-ac9719d0-c589-42cc-b893-0a37588626e1.jpg)

第二个 可以将动态照片移入二次展开栏 这样主界面不会拥挤 与12su一致 我是从thor类里面找到这段代码加入自己机型实现的 具体的跳转我没去找

.method public Oooooo0()[I
    .registers 1

    const/4 p0, 0x2

    new-array p0, p0, [I

    fill-array-data p0, :array_8

    return-object p0

    nop

    :array_8
    .array-data 4
        0xa30ce01
        0xa70d101
    .end array-data
.end method
谢谢

**Comment by a406010503** [comment]
感謝建議，但是Google Lens和超級微距也會在上面，這還是不能完全解決問題。

**Comment by Chen017** [comment]
ok
