### ISSUE TITLE
Dynamic Shot still not working 

### ISSUE THREAD

**Issue by abdoelbanaa** [a406010503/Miui_Camera#46]
Hi dynamic Shot still not working in 4.5.001800.5（450018005）
And latest version and not working please please fix it in run time

**Comment by abdoelbanaa** [comment]
Redmi note 10
Android 12

**Comment by a406010503** [comment]
Please specify... Does it not work or are you unable to use it?

**Comment by a406010503** [comment]
Since this question is no longer active, we will close this question.

Based on the problem you mentioned, we cannot guarantee that you can use the camera normally because your model is no longer supported, so we suggest you to return to the version before 1620, please understand.
