### ISSUE TITLE
刷了v4.5.002030.5 (230108)版后相机app消失无法使用相机

### ISSUE THREAD

**Issue by tkrave** [a406010503/Miui_Camera#49]
Phone: Xiaomi 12 (2201123G)

MIUI: 14.0.3.0.TLCCNXM Stable (xiaomi.eu)
Magisk 25.2 (25200)
Miui_Camera v4.5.002030.5 (230108)

试了dev版，一样相机app消失。Maybe跟之前的Issue#42 一样是更改版本號所致

**Comment by a406010503** [comment]
我們有發現到不管更改或不更改都有機會造成相機丟失（有些人始終不會），因此維持於更改版本號。
如果你確實遇到此問題，請閱讀修改說明步驟，完成 核心破解 (Core Patch) 程序。

**Comment by tkrave** [comment]
的确用了LSPosed+Core Patch之后APK可以安装。
谢谢。
