### ISSUE TITLE
请问最新版v4.5.002030.5 (230108)还能否做到无声街拍？

### ISSUE THREAD

**Issue by ssuyoungwu** [a406010503/Miui_Camera#50]
我试了一下(Magisk-MIUI_Camera-v221120-Pre-dev)这个版本是可以的，但是最新版已经不可以了，请问有其他手段做到无声吗，或者后续还会考虑做街拍模式下无声的功能吗？谢谢！

**Comment by a406010503** [comment]
理論來說已經有無聲了，如果不行的話就關閉徠卡訂製相機模式，在聲音設定裡選擇無聲相機。

**Comment by a406010503** [comment]
此問題已於 v4.5.002120.1 (230210) 版本中修正，我將關閉此 issue，如果您有其他需要，可重新提交新的 issue 或重新打開此 issue。

**Comment by ssuyoungwu** [comment]
确实已修正，感谢！
