### ISSUE TITLE
镜头切换BUG

### ISSUE THREAD

**Issue by Lewis-Peter** [a406010503/Miui_Camera#52]
在50MP模式时，切换到2X焦距大概率导致相机无法链接到镜头。特别是从相册返回相机页面时，必然出现该问题。设备小米11Ultra。

**Comment by a406010503** [comment]
徠卡模式在持有50MP的機型上會有這個變焦選項，因為12S與13系列都有這個新特性，在不適合的機型上因為調用了錯誤的鏡頭所以導致了這個問題，由於這是官方的問題，無法修復。
