### ISSUE TITLE
Not working on Miui 14 Android 13 ( MI global version )

### ISSUE THREAD

**Issue by xShihaBx** [a406010503/Miui_Camera#54]

**Comment by a406010503** [comment]
The information is not complete, please complete it within the next few days, otherwise I will close this question.

**Comment by xShihaBx** [comment]
I am using Miui 14 Android 13 (global rom ) device. Whenever I try to install any of those miui 14 modules my camera app is uninstalled everytime and I can not even install the apk file provided with the module so I had to uninstall the module and after restart my default camera app bring back.

**Comment by xShihaBx** [comment]
![Uploading Screenshot_2023-02-05-23-33-37-423_com.android.settings.jpg…]()

**Comment by xShihaBx** [comment]
![Screenshot_2023-02-05-23-33-37-423_com android settings](https://user-images.githubusercontent.com/106065024/218142284-fae7a687-f7e2-4497-9fbf-42fe75578519.jpg)

**Comment by a406010503** [comment]
Please read the [modification instructions](https://github.com/a406010503/Miui_Camera/blob/main/Leica_en.md) first, which will show you how to do the Core Patch process, and when you are done you can install the Apk directly.

Magisk module is still unstable on MIUI 14, we recommend you to use Core Patch program to install the camera app.
