### ISSUE TITLE
网络异常，无法使用全景等功能

### ISSUE THREAD

**Issue by TXMengXue** [a406010503/Miui_Camera#55]
![83a7f0593573da68c10df405b7f9346](https://user-images.githubusercontent.com/119848825/218305741-d5253bb5-94c3-4667-b481-14d9ab526e78.jpg)
开不开VPN都是一样

**Comment by a406010503** [comment]
問題無法復現，並且經多人測試亦同，請檢查您的網路連線環境或嘗試清除相機數據再次嘗試。

**Comment by TXMengXue** [comment]
网络环境没有问题，尝试多种网路环境都是报网络异常；
已清理相机数据，并尝试重装相机，但还是报网络异常

**Comment by a406010503** [comment]
我會建議你退回原相機看看能不能下載，相機 Mod 本身並沒有動過全景功能，因此這不是 Mod 的問題，如果原相機可以下載全景功能你可以嘗試升級上來看看是否正常使用。

**Comment by TXMengXue** [comment]
可是我原相机的安装包已经没了呀

**Comment by a406010503** [comment]
將相機 Mod 完整解除安裝，包含 Magisk 模組，移除後就會退回內建的原相機。

**Comment by TXMengXue** [comment]
正在尝试中

**Comment by TXMengXue** [comment]
还是不行

**Comment by a406010503** [comment]
原相機如果也是這樣你應該找小米反映...

**Comment by TXMengXue** [comment]
原相机已解决

**Comment by TXMengXue** [comment]
原相机问题为代理等级不足无法实现真全局代理

**Comment by a406010503** [comment]
沒有什麼可以幫的，只能請你自行測試可能的情況並解決問題。

**Comment by TXMengXue** [comment]
ok已经恢复正常了

**Comment by TXMengXue** [comment]
谢谢大佬
