### ISSUE TITLE
切换到人像，提示无法连接到相机，然后就自动关闭了

### ISSUE THREAD

**Issue by BigBigBIgMan** [a406010503/Miui_Camera#56]
切换到人像，提示无法连接到相机，然后就自动关闭了
![](https://github.com/BigBigBIgMan/test/blob/main/1676699953039.jpg)
https://github.com/BigBigBIgMan/test/blob/main/1676699953039.jpg

**Comment by a406010503** [comment]
沒有說機型、系統、相機版本、在此之前做了什麼，神仙也幫不了

**Comment by BigBigBIgMan** [comment]
> 沒有說機型、系統、相機版本、在此之前做了什麼，神仙也幫不了

红米k20 pro  MIUI13   相机版本HolyBear_free_4.5.002120.1（安装之前是4.3.003520.5）；
通过magisk安装最新版本，打开相机，切换到人像模式，就是提示无法连接到相机

**Comment by a406010503** [comment]
K20 系列很早之前就已不再支援，該 Mod 目前僅適配 小米10 以後、CIVI2 之前推出的機型，建議您使用早前的 4.3.004870.0 版本，或使用其他人的 Mod。

**Comment by BigBigBIgMan** [comment]
> K20 系列很早之前就已不再支援，該 Mod 目前僅適配 小米10 以後、CIVI2 之前推出的機型，建議您使用早前的 4.3.004870.0 版本，或使用其他人的 Mod。

好的，了解了
