### ISSUE TITLE
watermark Leica

### ISSUE THREAD

**Issue by jjoeshua** [a406010503/Miui_Camera#58]
I install apk version of MIUI camera , and it was after opening Leica, I have xiaomi 12t pro , I turn watermark and looks like this:  xiaomi12t pro | Leica , is it posible to remove that leica?

**Comment by jjoeshua** [comment]
supermoon option working? I also didnt find 200mp?

**Comment by a406010503** [comment]
I don't know, but there is a theory, 200MP is displayed as "Ultra Pixel" on
your model, and the super moon needs hardware support, and there may be a
chance that it cannot be used.

**Comment by jjoeshua** [comment]
I can open it, choose models and that , but wait for night to try to shoot..

**Comment by a406010503** [comment]
This issue will be closed as this issue is no longer active.
If you need anything later, you can reopen this issue or open a new issue.
